resource_types:
- name: docker-image-resource
  type: docker-image
  privileged: true
  source: 
    repository: ruby

resources:
  - name: bitcoin-src
    type: git
    source:
      uri: https://github.com/bitcoin/bitcoin.git
      branch: master
  - name: bitcoin-pipeline
    type: git
    source:
      uri: https://github.com/dbwest/bitcoin-pipeline.git
jobs:
- name: build
  
  plan:
  - get: bitcoin-pipeline
    trigger: true
  - get: bitcoin-src
  - task: build
    config:
      inputs:
      - name: bitcoin-src
      - name: bitcoin-pipeline
      platform: linux
      image_resource:
        type: docker-image-resource
      run:
        path: ls